version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    # Add any environment variables if needed
    # environment:
    #   - NODE_ENV=production 