version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_LOADUI_API_URL: http://localhost:1001/tokenmint/server/load-ui/
    container_name: token-bridge-ui
    ports:
      - "3000:80"
    networks:
      - tokenmint-ecosystem
    restart: unless-stopped

networks:
  tokenmint-ecosystem:
    external: true